# Generated by Django 3.1.2 on 2020-10-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermenu',
            name='icon',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='菜单图标'),
        ),
    ]
