# Generated by Django 3.1.2 on 2020-10-22 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201022_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermenu',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='$显示字段$__name', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='users.usermenu', verbose_name='父级菜单'),
        ),
    ]
