# Generated by Django 3.1.2 on 2020-10-16 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(error_messages={'blank': 'IP地址不能为空', 'unique': '该地址已存在，请不要重复添加'}, unique=True, verbose_name='IP')),
                ('hostname', models.CharField(error_messages={'unique': '该名称已存在，请不要重复添加'}, max_length=32, unique=True, verbose_name='主机名')),
                ('server_type', models.CharField(choices=[('physical', '物理机'), ('virtual', '虚拟机')], default='virtual', max_length=10, verbose_name='服务器类型')),
                ('status', models.CharField(choices=[('online', '上线'), ('offline', '下线')], default='offline', max_length=10, verbose_name='状态')),
                ('cpu_info', models.CharField(blank=True, max_length=128, null=True, verbose_name='CPU')),
                ('os', models.CharField(blank=True, max_length=64, null=True, verbose_name='系统')),
                ('os_kernel', models.CharField(blank=True, max_length=255, null=True, verbose_name='系统内核')),
                ('memory', models.CharField(blank=True, max_length=12, null=True, verbose_name='内存/G')),
                ('disk', models.CharField(blank=True, max_length=12, null=True, verbose_name='硬盘/G')),
                ('ctime', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('utime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '主机',
                'verbose_name_plural': '主机',
                'db_table': 'hosts',
            },
        ),
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': '该机房已存在，请不要重复添加'}, max_length=32, unique=True, verbose_name='机房')),
                ('ctime', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('utime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('servers', models.ManyToManyField(to='assets.Hosts')),
            ],
            options={
                'verbose_name': '机房',
                'verbose_name_plural': '机房',
                'db_table': 'idc',
            },
        ),
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='主机组名')),
                ('ctime', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('utime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('host', models.ManyToManyField(to='assets.Hosts')),
            ],
            options={
                'verbose_name': '主机组',
                'verbose_name_plural': '主机组',
                'db_table': 'hostgroup',
            },
        ),
    ]
