# Generated by Django 3.1.2 on 2020-10-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostgroup',
            name='host',
            field=models.ManyToManyField(help_text='$显示字段$__name', to='assets.Hosts', verbose_name='主机'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='servers',
            field=models.ManyToManyField(help_text='$显示字段$__name', to='assets.Hosts', verbose_name='主机'),
        ),
    ]
