# Generated by Django 3.1.2 on 2020-10-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dedicatedhosts',
            name='network',
        ),
        migrations.RemoveField(
            model_name='virtualhosts',
            name='network',
        ),
        migrations.AddField(
            model_name='clusters',
            name='overallstatus',
            field=models.CharField(default='green', max_length=32, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='virtualhosts',
            name='os',
            field=models.CharField(default='', max_length=64, verbose_name='系统名称'),
        ),
    ]
