# Generated by Django 3.1.2 on 2020-11-02 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dedicatedhosts',
            name='status',
            field=models.CharField(default='green', max_length=32, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='dedicatedhosts',
            name='vendor',
            field=models.CharField(default='', max_length=64, verbose_name='厂商'),
        ),
        migrations.AddField(
            model_name='virtualhosts',
            name='host',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='vms.dedicatedhosts'),
        ),
        migrations.AddField(
            model_name='virtualhosts',
            name='status',
            field=models.CharField(default='green', max_length=32, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='dedicatedhosts',
            name='name',
            field=models.GenericIPAddressField(unique=True, verbose_name='主机名'),
        ),
        migrations.AlterField(
            model_name='virtualhosts',
            name='ip',
            field=models.GenericIPAddressField(default='', verbose_name='IP'),
        ),
    ]
