# Generated by Django 3.1.2 on 2020-10-17 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clustrs',
            new_name='Clusters',
        ),
        migrations.RenameModel(
            old_name='InnateHosts',
            new_name='Dedicatedhosts',
        ),
        migrations.RenameModel(
            old_name='NetworkApaters',
            new_name='NetworkAdapters',
        ),
        migrations.AlterModelTable(
            name='dedicatedhosts',
            table='dedicatedhosts',
        ),
        migrations.AlterModelTable(
            name='networkadapters',
            table='networkadapters',
        ),
    ]
