# Generated by Django 3.1.2 on 2020-11-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0002_auto_20201102_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='dedicatedhosts',
            name='os',
            field=models.CharField(default='', max_length=64, verbose_name='系统'),
        ),
    ]
