# Generated by Django 3.1.2 on 2020-10-22 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0002_auto_20201017_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusters',
            name='datacenter',
            field=models.ForeignKey(help_text='DataCenters__name', on_delete=django.db.models.deletion.CASCADE, to='vms.datacenters', verbose_name='数据中心'),
        ),
        migrations.AlterField(
            model_name='datastores',
            name='datacenter',
            field=models.ForeignKey(help_text='DataCenters__name', on_delete=django.db.models.deletion.CASCADE, to='vms.datacenters', verbose_name='数据中心'),
        ),
        migrations.AlterField(
            model_name='dedicatedhosts',
            name='cluster',
            field=models.ForeignKey(help_text='Clusters__name', on_delete=django.db.models.deletion.CASCADE, to='vms.clusters', verbose_name='集群'),
        ),
        migrations.AlterField(
            model_name='dedicatedhosts',
            name='datacenter',
            field=models.ForeignKey(help_text='DataCenters__name', on_delete=django.db.models.deletion.CASCADE, to='vms.datacenters', verbose_name='数据中心'),
        ),
        migrations.AlterField(
            model_name='networkadapters',
            name='datacenter',
            field=models.ForeignKey(help_text='DataCenters__name', on_delete=django.db.models.deletion.CASCADE, to='vms.datacenters', verbose_name='数据中心'),
        ),
        migrations.AlterField(
            model_name='virtualhosts',
            name='datacenter',
            field=models.ForeignKey(help_text='DataCenters__name', on_delete=django.db.models.deletion.CASCADE, to='vms.datacenters'),
        ),
    ]
