# Generated by Django 3.1.2 on 2020-10-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0004_auto_20201022_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dedicatedhosts',
            name='datastore',
            field=models.ManyToManyField(help_text='$显示字段$__name', to='vms.DataStores', verbose_name='存储'),
        ),
        migrations.AlterField(
            model_name='dedicatedhosts',
            name='network',
            field=models.ManyToManyField(help_text='$显示字段$__name', to='vms.NetworkAdapters', verbose_name='网络'),
        ),
        migrations.AlterField(
            model_name='virtualhosts',
            name='network',
            field=models.ManyToManyField(help_text='$显示字段$__name', to='vms.NetworkAdapters', verbose_name='网络'),
        ),
    ]
