# Generated by Django 3.1.2 on 2020-10-22 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tyadmin_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tyadminemailverifyrecord',
            options={'verbose_name': '邮箱验证码', 'verbose_name_plural': '邮箱验证码'},
        ),
    ]
